### PR TITLE
Using correct method for closing dialog

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
@brandizzi Could you check @topolik comments?

**Comment by brandizzi** [comment]
@eduardolundgren yes. Actually, I'm working on it right now.

**Comment by brandizzi** [comment]
Hi @eduardolundgren. I just replied to Tomáš [there](https://github.com/brandizzi/liferay-plugins/commit/eeee59954857c7570e6daa6714c63ffcef2eb13a#commitcomment-4395574). You may want to take a look. Also, I updated the current branch with the changed I mentioned there.

**Comment by topolik** [comment]
Hi @brandizzi, awesome! Thanks :)

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/2234. [See changes here.](https://github.com/eduardolundgren/liferay-plugins/compare/feb75b9~2...feb75b9) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
