### PR TITLE
LPS-40761 Regenerate

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @brandizzi, @eduardolundgren,

Shouldn't check other tables which contain portletId as for example portletpreferences and portlet? Perhaps the preferences are different than the new ones (or not, I don't know) but keep dirty data in database is usually problematic in the future.

Thanks.

**Comment by brandizzi** [comment]
Hi @achaparro,

I agree, we should take a look at other tables. However, since (1) the problem with the layouts is much more urgent, (2) we need to review other tables with care and (3) the release is coming this week, I think it would be better to close LPS-40761 and open a new ticket for checking other tables. Do you agree?

**Comment by achaparro** [comment]
I agree with you, the issue for the layout table is much more urgent and it has to be included in the next release and we can wait a bit for the rest of the changes.

So, could you open that ticket in order to not to forget that task?

Thanks @brandizzi!

**Comment by brandizzi** [comment]
Done! https://issues.liferay.com/browse/LPS-40855

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/2142. [See changes here.](https://github.com/eduardolundgren/liferay-plugins/compare/da9287104a7cda9cf174c6b8f6a697dc311e71cb~1...da9287104a7cda9cf174c6b8f6a697dc311e71cb) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
