### PR TITLE
LPS-27469

### PR DESCRIPTION
**Pull request by fabiopezzutto**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Hello Fabio, 

Brian renamed the portlet. Can you rebase the pull first?

Thank you 

## 

Eduardo Lundgren
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by fabiopezzutto** [comment]
Ok, the changes has been reflected to rebased environment.

Thanks.

**Comment by fabiopezzutto** [comment]
Hello Eduardo,
I've committed the last changes about booking notification. It is ready for code review.

Thanks.

**Comment by eduardolundgren** [comment]
Merged and submitted. Thank you.

**Pull request closed without merging**
