### PR TITLE
LPS-17187

### PR DESCRIPTION
**Pull request by antonio-junior**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Merged and submitted to brianchandotcom, thanks.

**Comment by eduardolundgren** [comment]
Antonio, can you re-test after my source formatting?

https://github.com/brianchandotcom/liferay-plugins/pull/128

Thank you.

**Comment by antonio-junior** [comment]
I'm gonna do.

**Comment by antonio-junior** [comment]
Eduardo, no issues were found.
Thanks.

**Pull request closed without merging**
