### PR TITLE
LPS-30949 Regenerate

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
cc @marcellustavares

**Comment by marcellustavares** [comment]
Wow, nice pull request Adam!

**Comment by brandizzi** [comment]
I'm closing this to add some related features.

**Comment by brandizzi** [comment]
Reopening because, although there is still more work to be done, it will be easier to review if sent in another pull request. Sorry for the annoyance :)

**Comment by eduardolundgren** [comment]
Let me know when it's done for review. Thx.

**Comment by brandizzi** [comment]
Well, it is done already. This PR basically does some reorganization and eliminates bugs from the confirmation chain. However, I will send you another one which will add some features as well. If the current PR is fit to merge I'll explain the next one.

Thanks!

**Comment by brandizzi** [comment]
Hello, @eduardolundgren.

Here is the new, complete pull request with all changes needed (except for possible future improvements in messages). It encompasses some heavy refactoring but I believe the changes were made in commits small enough to be easily read.

Note that all the commits until     2c84b21 ("_LPS-30949 Regenerate_") are mostly focused on repairing the original issue [LPS-30949](http://issues.liferay.com/issue/LPS-30949) as well as other minor associated bugs. I tried to not make any big changes that were not needed to cope with the code. After that, there are some improvements I'm proposing to make the code still less redundant; these commits made changes that I have not seen anywhere in the Liferay codebase but that made sense in this specific context.

**Comment by brandizzi** [comment]
Hello, Eduardo.

As we talked, I moved a commit to another PR and it is already merged. I reworked the current PR so there will be no conflict anymore. The current branch was also rebased to a more recent master.

**Comment by eduardolundgren** [comment]
Adam, the pull request looks good. In order to submit to Liferay portal we need to segment it in multiple small pieces.

Could you resend each part divided by functionality, then when gets merged we move to the next chunk?

Thx.

**Comment by brandizzi** [comment]
Thank you, Eduardo. As I've noted elsewhere, I'm sending a small part through https://github.com/eduardolundgren/liferay-plugins/pull/194.

**Pull request closed without merging**
