### PR TITLE
LPS-28447

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Eduardo, I've made some source formatting changes. Could you check them out and verify that they're okay? The biggest change I made was to change the Panel to being a Dialog. We shouldn't have multiple UI components being used for the same purpose, as it just adds in one variation that breaks the standard UI. If we want to migrate all dialogs to Panel, we should do it globally. Also, I localized the strings for the buttons. If this all looks good, you can shoot it to Brian, but if you have any changes you wish to discuss, just let me know. Thanks Eduardo

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Agreed, when we deprecate the Dialog we could go trough all the old Dialogs and change them to Panel, although I would rather use the Panel in the Calendar seeing that the old Dialog is going to be deprecated on the next Alloy version. There is no reason to write old code knowing that it's going to be deprecated in few weeks.

What do you think? If you really want that we could do, but at first glance will cause duplicated work.

Thank you Nate.

**Comment by natecavanaugh** [comment]
Heya Eduardo,
I don't think we should have variations, mainly because until we update the API, we don't know what else may come up between then and now.
I want to avoid a state where we have inconsistent components, because we never know what may come up between then and now.
So if it will be a short time, then we won't have to use the old API for much longer, but if we get delayed in upgrading the API, we still have consistent components.

Thanks Eduardo,

**Comment by eduardolundgren** [comment]
That sounds reasonable. Let's stick with the old Dialogs then for now.

**Comment by eduardolundgren** [comment]
Merged and submitted. Thank you.

View just my changes: https://github.com/eduardolundgren/liferay-plugins/compare/natecavanaugh:e3123e3d33...81f60c987a

**Pull request closed without merging**
