### PR TITLE
LPS-43959

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
If so, how do we approve events for a group for example?

**Comment by Preston-Crary** [comment]
@eduardolundgren 
They can still approve of events, it just doesn't happen automatically.  If a user makes an event for a site they may not necessarily be going to that event, but if they make one for their own calendar they are.

**Comment by eduardolundgren** [comment]
This behavior is intentional and was discussed with @mhan810, Mike what do u think?

**Comment by mhan810** [comment]
Guys, this will cause other problems. In the 6.1 calendar, there's no concept of accepting events. How about we do this:
(1) Create a setting for a given calendar to "auto accept"
(2) If that setting is set, then go ahead and automatically accept. Otherwise, leave in pending.

**Comment by Preston-Crary** [comment]
@eduardolundgren
Okay, I'll add in two portal properties for these behaviors and resend.  Thanks for the feedback!

**Comment by eduardolundgren** [comment]
Thank you.

**Comment by eduardolundgren** [comment]
Waiting for the new pull.

**Comment by brandizzi** [comment]
Hey guys. How did this ticket evolved? Do we already have the new properties?

**Pull request closed without merging**
