### PR TITLE
LPS-39510 Escaping the content every time it is used, except when saving in the database

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Eduardo, this ticket is partially completed. We still have issues during the drag event because we think it's doubled escaped. Adam created a separate one to handle this LPS-40172. Thanks

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
The fix seems fine. If there are remaining problems feel free to send me. Thanks! <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/eduardolundgren/liferay-plugins/compare/marcellustavares:pull-request-86-LPS-39510...3cbf148a464283d15c393f05d29b741cfacd5648) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-plugins/pull/2059. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
